In [1]:
import pandas as pd

In [11]:
df1 = pd.DataFrame(data = [[1,2,'x'],[5,6,'y'],[9,10,'z']],columns = ['a','b','c'])
df2 = pd.DataFrame(data = [['x'],['y'],['z']],columns = ['f'])

In [8]:
df1.head()

   a   b  c
0  1   2  x
1  5   6  y
2  9  10  z

In [12]:
df1.head()

   a   b  c
0  1   2  x
1  5   6  y
2  9  10  z

pd - axis